// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    MessageCard: typeof import('./src/components/message/MessageCard.vue')['default']
    MessageContainer: typeof import('./src/components/message/MessageContainer.vue')['default']
    MessageDayDivider: typeof import('./src/components/message/MessageDayDivider.vue')['default']
    TheAppBar: typeof import('./src/components/TheAppBar.vue')['default']
    TheMessenger: typeof import('./src/components/message/TheMessenger.vue')['default']
    VAlert: typeof import('vuetify/lib')['VAlert']
    VApp: typeof import('vuetify/lib')['VApp']
    VBadge: typeof import('vuetify/lib')['VBadge']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VContent: typeof import('vuetify/lib')['VContent']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VImg: typeof import('vuetify/lib')['VImg']
    VMain: typeof import('vuetify/lib')['VMain']
    VProgressCircular: typeof import('vuetify/lib')['VProgressCircular']
    VProgressLinear: typeof import('vuetify/lib')['VProgressLinear']
    VSelect: typeof import('vuetify/lib')['VSelect']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbar: typeof import('vuetify/lib')['VToolbar']
    VToolbarItems: typeof import('vuetify/lib')['VToolbarItems']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}

export { }
